### PR TITLE
Add OpenTelemetry integration to gRPC messages

### LINKED ISSUE #147: Add OpenTelemetry tracing header and propagate traces
Add headers to all gRPC messages to propagate traces. See the Fabric [RFC](https://github.com/hyperledger/fabric-rfcs/pull/42) for reference.

### PR DESCRIPTION
**Pull request by atoulme**
Signed-off-by: Antoine Toulme <antoine@lunar-ocean.com>

Fixes #147

It introduces OpenTelemetry instrumentation of gRPC messages through tracing.

### CODE REVIEW

**Comment by bestbeforetoday** [comment]
@atoulme Could you open a Jira corresponding to this new feature, which we can link this PR to?
- https://jira.hyperledger.org/projects/FABJ

Any expected performance impact in default configuration? If not, this would be good to get in.

Activating the tracing in an integration test would give confidence that it actually works, so that would be good to include in this PR. Other than that, it just needs merge conflicts resolved, a clean build and for the PR to be marked as ready for review.

**Comment by atoulme** [comment]
Sorry, I have no privileges to create issues in this project, from what I can see. There is no performance impact to add tracing. If it is disabled, traces will not propagate.
I can definitely update and get ready for merge.

**Comment by ryjones** [comment]
@bestbeforetoday per @denyeart I've disabled the ability to create new issues in Jira for Fabric projects. Fabric projects are migrating to GitHub issues.

**Comment by bestbeforetoday** [comment]
Yes, please go ahead and open a GitHub issue for this project, and then the PR can be linked to the issue: 

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by atoulme** [comment]
@bestbeforetoday ready for your review?

**Review by bestbeforetoday — APPROVED** [review]
👍

**Comment by bestbeforetoday** [comment]
If you want to include this in the v2.2.x releases, could you cherry-pick the commit from the _main_ branch to _release-2.2_ branch and raise a PR there?

**Comment by atoulme** [comment]
I will do that now.

**Comment by ryjones** [comment]
I think there is a tool to do that automagically

**Comment by ryjones** [comment]
@Mergifyio backport release-2.2

**Pull request merged**
