### PR TITLE
Move Azure pipeline file to correct location.

### PR DESCRIPTION
**Pull request by lehors**
This change makes this repo compliant with HLP common repo structure.

Note: this PR requires updating the Github CI configuration as well.

Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>

### CODE REVIEW

**Comment by btl5037** [comment]
To do this requires two PR's, the needs to have both the old, and the new pipeline file. Then we need to update Azure to point to the new file, then a second PR to delete the old pipeline file.

**Comment by lehors** [comment]
Or @rjones overrides all the checks and get it all done at once. :-)

**Comment by bestbeforetoday** [comment]
Please don't subvert the build process and risk getting the build into a failing state

**Comment by bestbeforetoday** [comment]
This PR has been stale for a year so closing.

**Pull request closed without merging**
